/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import util.BGM;
import util.DBcls;
import util.Language;
import util.MyLookAndFeel;
import util.Mypanel;
import util.UiUtil;
import User.Login;
import User.Message3;
import User.Status;
import User.Studentstatus;

/**
 *
 * 这是主界面窗�? * @author wangming
 */
public class TheMainUI extends javax.swing.JFrame implements Runnable {

	public static int SID;
	public static JFrame frame;
	Connection con;
	PreparedStatement ps;
	ResultSet rs;
	BGM bgm = new BGM();
	Thread t=null;
	/**
	     * 
	     */
	public TheMainUI() {
	    	if(t==null) {
	    	t = new Thread(this, "0");
		
	    	}
	    	t.start();
		frame = this;
		setContentPane(new Mypanel());
		initComponents();
		init();
		if (Login.type.equals("student")) {
			String sql[] = { "select SID from studetail where sname=?" };

			try {
				con = DBcls.getcon();
				ps = con.prepareStatement(sql[0]);
				ps.setString(1, Login.name);
				System.out.println(ps);
				rs = ps.executeQuery();
				rs.next();
				this.SID = SelectLesson.SID = rs.getInt(1);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			userManagement.setEnabled(false);
			course.setEnabled(false);
		} else if (Login.type.equals("teacher")) {

			userManagement.setEnabled(false);
			selectLesson.setEnabled(false);
			course.setEnabled(false);
			studentStatus.setEnabled(false);
		} else {

			result.setEnabled(false);
			selectLesson.setEnabled(false);
		}
		aaa.setText("Welcome: " + Login.name);
	}

	public void init() {
		// 设置窗体居中
	    	UiUtil.setFrameImage(this, 3);
		setLocationRelativeTo(null);
		addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent e) {
				int option = JOptionPane.showConfirmDialog(TheMainUI.this, "确认退出?", "提示", JOptionPane.YES_NO_OPTION);
				if (option == JOptionPane.YES_OPTION) {
					System.exit(0);
				} else {
				}
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		aaa = new javax.swing.JLabel();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuBar1 = new javax.swing.JMenuBar();
		file = new javax.swing.JMenu();
		skin = new javax.swing.JMenu();
		skin1 = new javax.swing.JMenuItem();
		skin2 = new javax.swing.JMenuItem();
		skin3 = new javax.swing.JMenuItem();
		skin4 = new javax.swing.JMenuItem();
		skin5 = new javax.swing.JMenuItem();
		skin6 = new javax.swing.JMenuItem();
		skin7 = new javax.swing.JMenuItem();
		skin8 = new javax.swing.JMenuItem();
		skin9 = new javax.swing.JMenuItem();
		skin10 = new javax.swing.JMenuItem();
		skin11 = new javax.swing.JMenuItem();
		skin12 = new javax.swing.JMenuItem();
		skin13 = new javax.swing.JMenuItem();
		skin14 = new javax.swing.JMenuItem();
		skin15 = new javax.swing.JMenuItem();
		skin16 = new javax.swing.JMenuItem();
		skin17 = new javax.swing.JMenuItem();
		welcome = new javax.swing.JMenuItem();
		chinese = new javax.swing.JMenuItem();
		english = new javax.swing.JMenuItem();
		userManagement = new javax.swing.JMenuItem();
		studentStatus = new javax.swing.JMenuItem();
		selectLesson = new javax.swing.JMenuItem();
		result = new javax.swing.JMenuItem();
		course = new javax.swing.JMenuItem();
		passwordManagement = new javax.swing.JMenuItem();
		exit = new javax.swing.JMenuItem();
		edit = new javax.swing.JMenu();
		language = new javax.swing.JMenu();
		pg = new javax.swing.JMenu();
		pg1 = new javax.swing.JMenuItem();
		pg2 = new javax.swing.JMenuItem();
		pg3 = new javax.swing.JMenuItem();
		pg4 = new javax.swing.JMenuItem();
		defaultSet = new javax.swing.JMenuItem();
		changebg = new javax.swing.JMenu();
		m1 = new javax.swing.JMenuItem();
		jMenuItem20 = new javax.swing.JMenuItem();
		jMenuItem21 = new javax.swing.JMenuItem();
		jMenuItem22 = new javax.swing.JMenuItem();
		jMenuItem10 = new javax.swing.JMenuItem();
		game = new javax.swing.JMenu();
		jMenuItem11 = new javax.swing.JMenuItem();
		jMenuItem12 = new javax.swing.JMenuItem();
		jMenuItem13 = new javax.swing.JMenuItem();
		jMenuItem14 = new javax.swing.JMenuItem();

		jMenuItem6.setText("jMenuItem6");

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setResizable(false);
		
		language.setText("language");
		
		chinese.setText("中文");
		chinese.addActionListener(e -> {
		    
			Language.chineseLanguage();
			
		    welcomeAction(e);
		});
		language.add(chinese);
		
		english.setText("English");
		english.addActionListener(new ActionListener() {
		    
		    @Override
		    public void actionPerformed(ActionEvent e) {
			
			Language.englishLanguage();
			
			welcomeAction(e);
		    }
		});
		language.add(english);
		
		file.setText(Language.file);

		welcome.setText(Language.welcome);
		welcome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				welcomeAction(evt);
			}
		});
		file.add(welcome);

		userManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
		userManagement.setText(Language.userManagement);
		userManagement.addActionListener(e -> {
		    this.setContentPane(new Message3());
			setVisible(true);
		});
		file.add(userManagement);

		studentStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
		studentStatus.setText(Language.studentStatus);
		studentStatus.addActionListener(e -> {
			Status st = new Status();
			if (Login.type.equals("student")) {
				int i = 0;
				for (;; i++) {
					if (st.info[i][1].equals(Login.name))
						break;
				}
				this.setContentPane(new Studentstatus(st.info[i]));
			} else {
				this.setContentPane(st);
			}
			this.setVisible(true);
		});
		file.add(studentStatus);

		selectLesson.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
		selectLesson.setText(Language.selectLesson);
		selectLesson.addActionListener(e -> {
		    	// 进入选课界面
			this.setContentPane(new SelectLesson());
			this.setVisible(true);
		});
		file.add(selectLesson);

		result.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
		result.setText(Language.result);
		result.addActionListener(e -> {
		    	// 进入成绩界面
			this.setContentPane(new Score());
			this.setVisible(true);
		});
		file.add(result);

		course.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
		course.setText(Language.course);
		course.addActionListener(e -> {
		    	// 进入课程管理界面
			this.setContentPane(new Menu().parent);
			this.setVisible(true);
		});
		file.add(course);

		passwordManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
		passwordManagement.setText(Language.passwordManagement);
		passwordManagement.addActionListener(e -> {
			this.setContentPane(new Passwordmanagement());
			this.setVisible(true);
		});
		file.add(passwordManagement);

		exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
		exit.setText(Language.exit);
		exit.addActionListener(e -> System.exit(0));
		file.add(exit);

		jMenuBar1.add(file);

		edit.setText(Language.edit);
		skin.setText(Language.skin);
		skin1.setText("1");
		skin1.addActionListener(e -> {
		    MyLookAndFeel.model1();
		    this.setVisible(true);
		});
		skin2.setText("2");
		skin2.addActionListener(e -> {
		    MyLookAndFeel.model2();
		    welcomeAction(e);
		});
		skin3.setText("3");
		skin3.addActionListener(e -> {
		    MyLookAndFeel.model3();
		    welcomeAction(e);
		});
		skin4.setText("4");
		skin4.addActionListener(e -> {
		    MyLookAndFeel.model4();
		    welcomeAction(e);
		});
		skin5.setText("5");
		skin5.addActionListener(e -> {
		    MyLookAndFeel.model5();
		    welcomeAction(e);
		});
		//12个
		skin6.setText("6");
		skin6.addActionListener(e -> {
		    MyLookAndFeel.model6();
		    this.setVisible(true);
		});
		skin7.setText("7");
		skin7.addActionListener(e -> {
		    MyLookAndFeel.model7();
		    welcomeAction(e);
		});
		skin8.setText("8");
		skin8.addActionListener(e -> {
		    MyLookAndFeel.model8();
		    welcomeAction(e);
		});
		skin9.setText("9");
		skin9.addActionListener(e -> {
		    MyLookAndFeel.model9();
		    welcomeAction(e);
		});
		skin10.setText("10");
		skin10.addActionListener(e -> {
		    MyLookAndFeel.model10();
		    welcomeAction(e);
		});
		skin11.setText("11");
		skin11.addActionListener(e -> {
		    MyLookAndFeel.model11();
		    this.setVisible(true);
		});
		skin12.setText("12");
		skin12.addActionListener(e -> {
		    MyLookAndFeel.model12();
		    welcomeAction(e);
		});
		skin13.setText("13");
		skin13.addActionListener(e -> {
		    MyLookAndFeel.model13();
		    welcomeAction(e);
		});
		skin14.setText("14");
		skin14.addActionListener(e -> {
		    MyLookAndFeel.model14();
		    welcomeAction(e);
		});
		skin15.setText("15");
		skin15.addActionListener(e -> {
		    MyLookAndFeel.model15();
		    welcomeAction(e);
		});
		skin16.setText("16");
		skin16.addActionListener(e -> {
		    MyLookAndFeel.model16();
		    this.setVisible(true);
		});
		skin17.setText("17");
		skin17.addActionListener(e -> {
		    MyLookAndFeel.model17();
		    welcomeAction(e);
		});
		skin.add(skin1);
		skin.add(skin2);
		skin.add(skin3);
		skin.add(skin4);
		skin.add(skin5);
		skin.add(skin6);
		skin.add(skin7);
		skin.add(skin8);
		skin.add(skin9);
		skin.add(skin10);
		skin.add(skin11);
		skin.add(skin12);
		skin.add(skin13);
		skin.add(skin14);
		skin.add(skin15);
		skin.add(skin16);
		skin.add(skin17);
		edit.add(skin);
		pg.setText(Language.pg);
		pg1.setText("1");
		pg1.addActionListener(e -> {
		    	Mypanel.setp(0);
			welcomeAction(e);
		});
		pg.add(pg1);

		pg2.setText("2");
		pg2.addActionListener(e -> {
		    	Mypanel.setp(1);
			welcomeAction(e);
		});
		pg.add(pg2);

		pg3.setText("3");
		pg3.addActionListener(e -> {
		    	Mypanel.setp(2);
			welcomeAction(e);
		});
		pg.add(pg3);

		pg4.setText("4");
		pg4.addActionListener(e -> {
		    	Mypanel.setp(3);
			welcomeAction(e);
		});
		pg.add(pg4);

		defaultSet.setText(Language.defaultSet);
		defaultSet.addActionListener(e -> {
		    	Mypanel.setp(0);
			welcomeAction(e);
		});
		pg.add(defaultSet);

		edit.add(pg);

		changebg.setText(Language.chagebg);

		m1.setText("1");
		m1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				musicChangeAction(0);
			}
		});
		changebg.add(m1);

		jMenuItem20.setText("2");
		jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				musicChangeAction(1);
			}
		});
		changebg.add(jMenuItem20);

		jMenuItem21.setText("3");
		jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				musicChangeAction(2);
			}
		});
		changebg.add(jMenuItem21);

		jMenuItem22.setText("4");
		jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				musicChangeAction(3);
			}
		});
		changebg.add(jMenuItem22);

		jMenuItem10.setText(Language.defaultSet);
		jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				musicChangeAction(0);
			}
		});
		changebg.add(jMenuItem10);
		edit.add(changebg);

		jMenuBar1.add(edit);

		game.setText(Language.game);

		jMenuItem12.setText("Hearts");
		jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem12ActionPerformed(evt);
			}
		});
		game.add(jMenuItem12);

		jMenuItem13.setText("Solitaire");
		jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem13ActionPerformed(evt);
			}
		});
		game.add(jMenuItem13);

		jMenuItem14.setText("FreeCell");
		jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem14ActionPerformed(evt);
			}
		});
		game.add(jMenuItem14);

		jMenuBar1.add(game);
		jMenuBar1.add(language);
		setJMenuBar(jMenuBar1);
		aaa.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
		aaa.setText("jLabel1");
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(127, 127, 127).addComponent(aaa,
								javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(159, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(130, 130, 130).addComponent(aaa,
								javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(332, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void welcomeAction(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	    	t.stop();
		this.dispose();
		new TheMainUI().setVisible(true);
	}

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem8ActionPerformed
		// TODO add your handling code here:
		this.setContentPane(new Passwordmanagement());
		this.setVisible(true);
	}// GEN-LAST:event_jMenuItem8ActionPerformed

	private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem11ActionPerformed
		Runtime r = Runtime.getRuntime();
		String cmd = getcmd1();
		try {
			r.exec(cmd + "Chess.exe");
		} catch (IOException ex) {
			Logger.getLogger(TheMainUI.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jMenuItem11ActionPerformed

	private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem12ActionPerformed
		Runtime r = Runtime.getRuntime();
		String cmd = getcmd1();
		try {
			r.exec(cmd + "Hearts.lnk");
		} catch (IOException ex) {
			Logger.getLogger(TheMainUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jMenuItem12ActionPerformed

	private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem13ActionPerformed
		Runtime r = Runtime.getRuntime();
		String cmd = getcmd1();
		try {
			r.exec(cmd + "Solitaire.lnk");
		} catch (IOException ex) {
			Logger.getLogger(TheMainUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jMenuItem13ActionPerformed

	private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem14ActionPerformed
		Runtime r = Runtime.getRuntime();
		String cmd = getcmd1();
		try {
			r.exec(cmd + "FreeCell.lnk");
		} catch (IOException ex) {
			Logger.getLogger(TheMainUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jMenuItem14ActionPerformed

	public String getcmd1() {
		File directory = new File("");// 参数为空
		String courseFile = null;
		try {
			courseFile = directory.getCanonicalPath();
		} catch (IOException ex) {
			Logger.getLogger(TheMainUI.class.getName()).log(Level.SEVERE, null, ex);
		}
		courseFile += "\\src\\resource\\game\\";
		System.out.println(courseFile);
		String cmd1 = "cmd /C Start ";
		cmd1 += courseFile;
		return cmd1;
	}

//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                frame = new NewJFrame();
//                frame.setVisible(true);
//            }
//        });
//    }
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel aaa;
	private javax.swing.JMenu file;
	private javax.swing.JMenuItem skin;
	private javax.swing.JMenuItem skin1;
	private javax.swing.JMenuItem skin2;
	private javax.swing.JMenuItem skin3;
	private javax.swing.JMenuItem skin4;
	private javax.swing.JMenuItem skin5;
	private javax.swing.JMenuItem skin6;
	private javax.swing.JMenuItem skin7;
	private javax.swing.JMenuItem skin8;
	private javax.swing.JMenuItem skin9;
	private javax.swing.JMenuItem skin10;
	private javax.swing.JMenuItem skin11;
	private javax.swing.JMenuItem skin12;
	private javax.swing.JMenuItem skin13;
	private javax.swing.JMenuItem skin14;
	private javax.swing.JMenuItem skin15;
	private javax.swing.JMenuItem skin16;
	private javax.swing.JMenuItem skin17;
	private javax.swing.JMenu edit;
	private javax.swing.JMenu language;
	private javax.swing.JMenu game;
	private javax.swing.JMenu pg;
	private javax.swing.JMenu changebg;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem exit;
	private javax.swing.JMenuItem jMenuItem10;
	private javax.swing.JMenuItem jMenuItem11;
	private javax.swing.JMenuItem jMenuItem12;
	private javax.swing.JMenuItem jMenuItem13;
	private javax.swing.JMenuItem jMenuItem14;
	private javax.swing.JMenuItem welcome;
	private javax.swing.JMenuItem chinese;
	private javax.swing.JMenuItem english;
	private javax.swing.JMenuItem pg1;
	private javax.swing.JMenuItem pg2;
	private javax.swing.JMenuItem pg3;
	private javax.swing.JMenuItem m1;
	private javax.swing.JMenuItem userManagement;
	private javax.swing.JMenuItem jMenuItem20;
	private javax.swing.JMenuItem jMenuItem21;
	private javax.swing.JMenuItem jMenuItem22;
	private javax.swing.JMenuItem pg4;
	private javax.swing.JMenuItem studentStatus;
	private javax.swing.JMenuItem selectLesson;
	private javax.swing.JMenuItem result;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem course;
	private javax.swing.JMenuItem passwordManagement;
	private javax.swing.JMenuItem defaultSet;
	// End of variables declaration//GEN-END:variables

	private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void musicChangeAction(int i) {
	    	t.stop();
		t = new Thread(this, "" + i);
		t.start();
	}

	@Override
	public void run() {

		if (Thread.currentThread().getName().equals("0"))
			bgm.MUSIC(0);
		if (Thread.currentThread().getName().equals("1"))
			bgm.MUSIC(1);
		if (Thread.currentThread().getName().equals("2"))
			bgm.MUSIC(2);
		if (Thread.currentThread().getName().equals("3"))
			bgm.MUSIC(3);
		throw new UnsupportedOperationException("Not supported yet.");
	}
}
