/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import systemUI.TheMainUI;
import util.DBcls;
import util.Language;
import util.MyLookAndFeel;
import util.UiUtil;

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    public static String type;
    public static String name;

    public static JFrame frame;

    /**
     * Creates new form Login2
     */
    public Login() {
	
	Language.chineseLanguage();
	
	frame = this;
	initComponents();
	this.setLocationRelativeTo(null);
	this.setResizable(false);
	UiUtil.setFrameImage(this, 2);
	setitems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	ok = new javax.swing.JButton();
	newUser = new javax.swing.JButton();
	cancel = new javax.swing.JButton();
	usernamelebel = new javax.swing.JLabel();
	passWordlebel = new javax.swing.JLabel();
	Password = new javax.swing.JPasswordField();
	username = new javax.swing.JComboBox();
	loginlebel = new javax.swing.JLabel();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	ok.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
	ok.setText("OK");
	// 进入登录界面
	ok.addActionListener(e -> {
	    String sql[] = { "Select * from users where name=? and password=?" };
	    TheMainUI n =null;
	    	try {
		    con = DBcls.getcon();
		    ps = con.prepareStatement(sql[0]);
		    ps.setString(1, username.getSelectedItem().toString());
		    ps.setString(2, Password.getText());
		    rs = ps.executeQuery();
		    if (username.getSelectedItem().toString().length() == 0) {
			JOptionPane.showMessageDialog(this, "UserName could'n be Null");
			return;
		    }
		    if (Password.getText().length() == 0) {
			JOptionPane.showMessageDialog(this, "Password could'n be Null");
			return;
		    }
		    if (rs.next()) {
			type = rs.getString(2);
			name = rs.getString(1);
			
			n= new TheMainUI();
//			Language.chineseLanguage();
			this.dispose();
			n.setVisible(true);
		    } else {
			JOptionPane.showMessageDialog(this,
				"The UserName and Password do not match");
		    }

		} catch (Exception ex) {
		    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
		}finally{
		    
		}
		
	});

	newUser.setText("NewUser");
	// 进入注册界面的事件
	newUser.addActionListener(e -> {
	    this.setContentPane(new Register());
		this.setVisible(true);
	});

	cancel.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
	cancel.setText("Cancel");
	cancel.addActionListener(e -> {
	    System.exit(0);
	});

	usernamelebel.setFont(new java.awt.Font("宋体", 2, 24)); // NOI18N
	usernamelebel.setText("   UserName");

	passWordlebel.setFont(new java.awt.Font("宋体", 2, 24)); // NOI18N
	passWordlebel.setText("   Password");

	username.setEditable(true);

	loginlebel.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
	loginlebel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	loginlebel.setText("LOGIN");

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
		getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			javax.swing.GroupLayout.Alignment.TRAILING,
			layout.createSequentialGroup()
				.addGap(102, 102, 102)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(
							usernamelebel,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							150,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(
							passWordlebel,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							150,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED,
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING,
						false)
						.addComponent(
							username,
							0,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							Short.MAX_VALUE)
						.addComponent(
							Password,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							181,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(73, 73, 73))
		.addGroup(
			javax.swing.GroupLayout.Alignment.TRAILING,
			layout.createSequentialGroup()
				.addContainerGap(167, Short.MAX_VALUE)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
							javax.swing.GroupLayout.Alignment.TRAILING,
							layout.createSequentialGroup()
								.addComponent(
									newUser)
								.addGap(60, 60,
									60))
						.addGroup(
							javax.swing.GroupLayout.Alignment.TRAILING,
							layout.createSequentialGroup()
								.addComponent(
									loginlebel,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									414,
									javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(119,
									119,
									119))))
		.addGroup(
			layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
					layout.createSequentialGroup()
						.addGap(131, 131, 131)
						.addComponent(
							ok,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							111,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(162, 162, 162)
						.addComponent(
							cancel,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							123,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(173,
							Short.MAX_VALUE))));
	layout.setVerticalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addGap(0, 36, Short.MAX_VALUE)
				.addComponent(loginlebel,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					117,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING,
						false)
						.addComponent(
							usernamelebel,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							Short.MAX_VALUE)
						.addComponent(
							username,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							37,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(114, 114, 114)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
							layout.createSequentialGroup()
								.addComponent(
									Password,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									37,
									javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(4, 4, 4))
						.addComponent(
							passWordlebel,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							41,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(144, 144, 144).addComponent(newUser)
				.addGap(70, 70, 70))
		.addGroup(
			layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
					layout.createSequentialGroup()
						.addContainerGap(418,
							Short.MAX_VALUE)
						.addGroup(
							layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(
									ok,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									38,
									javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(
									cancel,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									38,
									javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(144, 144, 144))));

	pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase
	 * /tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
		    .getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	// </editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		// skinpool.skin(2);
		MyLookAndFeel.model4();
		new Login().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel loginlebel;
    private javax.swing.JComboBox username;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    private javax.swing.JButton newUser;
    private javax.swing.JLabel usernamelebel;
    private javax.swing.JLabel passWordlebel;

    // End of variables declaration//GEN-END:variables
    void setitems() {
	String sql[] = { "select name from users" };
	try {
	    con = DBcls.getcon();
	    ps = con.prepareStatement(sql[0]);
	    rs = ps.executeQuery();
	    while (rs.next()) {
		username.addItem(rs.getString(1));
	    }
	} catch (Exception e) {
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}
    }
}
