/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import systemUI.TheMainUI;
import util.DBcls;
import util.Mypanel;

/**
 *
 * @author 23155
 */
public class Status extends Mypanel implements Runnable {

	public static int selectedID;
	public Object[][] tab, info;
	Connection con;
	PreparedStatement ps;
	Statement st;
	ResultSet rs;
	int[] id;

	/**
	 * Creates new form Status
	 */
	public Status() {
		initComponents();
		settable();
		
		new Thread(this).start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		abc2 = new javax.swing.JTable();
		abc1 = new javax.swing.JButton();

		jLabel1.setFont(new java.awt.Font("宋体", 3, 48)); // NOI18N
		jLabel1.setText(" Status");

		abc2.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
		abc2.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null } },
						new String[] { "Name", "Sex" }) {
					boolean[] canEdit = new boolean[] { false, false };

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jScrollPane1.setViewportView(abc2);
		abc2.getColumnModel().getColumn(0).setResizable(false);
		abc2.getColumnModel().getColumn(1).setResizable(false);

		abc1.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
		abc1.setText("Details");
		abc1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				abc1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap(136, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(112, 112, 112))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(212, 212, 212))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addComponent(abc1, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(273, 273, 273)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(25, 25, 25).addComponent(jLabel1).addGap(33, 33, 33)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
				.addComponent(abc1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(39, 39, 39)));
	}// </editor-fold>//GEN-END:initComponents

	private void abc1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_abc1ActionPerformed
		// TODO add your handling code here:
		TheMainUI.frame.setContentPane(new Studentstatus(info[abc2.getSelectedRow()]));
		TheMainUI.frame.setVisible(true);

	}// GEN-LAST:event_abc1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton abc1;
	private javax.swing.JTable abc2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables
	void settable() {
		String sql[] = { "select count(SID) from studetail", "select * from studetail" };
		try {
			con = DBcls.getcon();
			ps = con.prepareStatement(sql[0]);
			rs = ps.executeQuery();
			int row = 0;
			if (rs.next())
				row = rs.getInt(1);

			tab = new Object[row][2];
			info = new Object[row][9];
			int i = 0;
			ps = con.prepareStatement(sql[1]);
			rs = ps.executeQuery();
			while (rs.next()) {
				info[i][0] = rs.getInt(1);
				for (int j = 1; j < 9; j++)
					info[i][j] = rs.getString(j + 1);
				tab[i][0] = rs.getString(3);
				tab[i][1] = rs.getString(6);
				i++;
			}
			abc2.setModel(new javax.swing.table.DefaultTableModel(tab, new String[] { "Name", "Sex" }) {
				boolean[] canEdit = new boolean[] { false, false };

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			});

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}

	@Override
	public void run() {
		while (true) {
			try {
				Thread.sleep(100);
			} catch (Exception e) {
				e.printStackTrace();
			}
			if (abc2.getSelectedRow() > -1) {
				abc1.setEnabled(true);
			} else {
				abc1.setEnabled(false);
			}
		}
	}
}
