/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;

import systemUI.TheMainUI;
import util.DBcls;
import util.Mypanel;

/**
 *
 * @author 23155
 */
public class Studentstatus extends Mypanel implements Runnable {

	public static int selectedID;
	Object[] info;
	Connection con;
	PreparedStatement ps;
	Statement st;
	ResultSet rs;

	/**
	 * Creates new form Studentstatus
	 */
	public Studentstatus(Object[] info) {
		this.info = info;
		initComponents();
		setinfo();
		jButton2.setVisible(false);
		jButton3.setVisible(false);
		qwe.setEditable(false);
		qwe1.setEditable(false);
		qwe2.setEditable(false);
		qwe3.setEditable(false);
		qwe4.setEditable(false);
		qwe5.setEditable(false);
		new Thread(this).start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		qwe = new javax.swing.JTextField();
		qwe1 = new javax.swing.JTextField();
		qwe2 = new javax.swing.JTextField();
		qwe3 = new javax.swing.JTextField();
		qwe4 = new javax.swing.JTextField();
		qwe5 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();

		setLayout(null);

		jLabel1.setFont(new java.awt.Font("宋体", 3, 48)); // NOI18N
		jLabel1.setText("StudentStatus");
		add(jLabel1);
		jLabel1.setBounds(170, 20, 369, 56);

		jLabel2.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel2.setText("  Name");
		add(jLabel2);
		jLabel2.setBounds(112, 113, 127, 35);

		jLabel3.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel3.setText(" Student Number");
		add(jLabel3);
		jLabel3.setBounds(91, 180, 278, 35);

		jLabel4.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel4.setText("   Sex");
		add(jLabel4);
		jLabel4.setBounds(91, 233, 133, 35);

		jLabel5.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel5.setText("  Academy");
		add(jLabel5);
		jLabel5.setBounds(91, 400, 207, 35);

		jLabel6.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel6.setText("  ID Card");
		add(jLabel6);
		jLabel6.setBounds(91, 286, 278, 35);

		jLabel7.setFont(new java.awt.Font("宋体", 2, 30)); // NOI18N
		jLabel7.setText("  Major");
		add(jLabel7);
		jLabel7.setBounds(91, 347, 165, 35);

		jButton1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
		jButton1.setText("Edit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		add(jButton1);
		jButton1.setBounds(590, 40, 80, 25);

		jButton2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
		jButton2.setText("Save");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		add(jButton2);
		jButton2.setBounds(130, 520, 100, 32);

		jButton3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
		jButton3.setText("Cancel");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		add(jButton3);
		jButton3.setBounds(310, 520, 100, 32);
		add(qwe);
		qwe.setBounds(400, 113, 230, 35);
		add(qwe1);
		qwe1.setBounds(400, 180, 230, 29);
		add(qwe2);
		qwe2.setBounds(400, 227, 230, 35);
		add(qwe3);
		qwe3.setBounds(400, 294, 230, 35);
		add(qwe4);
		qwe4.setBounds(400, 347, 230, 35);
		add(qwe5);
		qwe5.setBounds(400, 400, 230, 35);

		jButton4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
		jButton4.setText("Back");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				jButton4ActionPerformed(evt);
			}
		});

		
			add(jButton4);
		jButton4.setBounds(480, 520, 100, 32);
		jButton4.setVisible(true);
		if (Login.type.equals("student"))
			jButton4.setVisible(false);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:

		jButton4.setVisible(true);
		if (Login.type.equals("student"))
			jButton4.setVisible(false);
		jButton2.setVisible(true);
		jButton3.setVisible(true);
		qwe.setEditable(true);
		qwe1.setEditable(true);
		qwe2.setEditable(true);
		qwe3.setEditable(true);
		qwe4.setEditable(true);
		qwe5.setEditable(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		jButton2.setVisible(false);
		jButton3.setVisible(false);
		qwe.setEditable(false);
		qwe1.setEditable(false);
		qwe2.setEditable(false);
		qwe3.setEditable(false);
		qwe4.setEditable(false);
		qwe5.setEditable(false);
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		String sql[] = {
				"update studetail set realname=?,student_number=?,sex=?,ID_card=?,major=?,academy=? where SID=?" };

		try {
			con = DBcls.getcon();
			ps = con.prepareStatement(sql[0]);
			ps.setString(1, qwe.getText());
			ps.setString(2, qwe1.getText());
			ps.setString(3, qwe2.getText());
			ps.setString(4, qwe3.getText());
			ps.setString(5, qwe4.getText());
			ps.setString(6, qwe5.getText());
			ps.setInt(7, new Integer(info[0].toString()));
			if (ps.executeUpdate() > 0)
				JOptionPane.showMessageDialog(this, "Succeeded");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		TheMainUI.frame.setContentPane(new Status());
		TheMainUI.frame.setVisible(true);
	}// GEN-LAST:event_jButton4ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField qwe;
	private javax.swing.JTextField qwe1;
	private javax.swing.JTextField qwe2;
	private javax.swing.JTextField qwe3;
	private javax.swing.JTextField qwe4;
	private javax.swing.JTextField qwe5;

	// End of variables declaration//GEN-END:variables
	void setinfo() {
		for (int i = 0; i < 9; i++) {
			System.out.println(info[i]);
		}
		qwe.setText(info[2].toString());
		qwe1.setText((String) info[4]);
		qwe2.setText((String) info[5]);
		qwe3.setText((String) info[6]);
		qwe4.setText((String) info[7]);
		qwe5.setText((String) info[8]);
	}

	@Override
	public void run() {

	}
}
